### ISSUE TITLE
JWT Package wird nicht weiter maintained. Ersetzen durch Fork?

### ISSUE THREAD

**Issue by 13ue** [c3ai-lab/cryptoAcademy#103]
[Das hier](https://github.com/PHP-Open-Source-Saver/jwt-auth) ist ein Fork von unserem JWT Package, welcher noch weiter maintained wird. Als sicherheitsrelevantes Package in der Authentifizierung sollten wir eine Migration zu diesem erwägen.

**Comment by magdalenatsolaki** [comment]
erledigt, und laravel auf versin 9 geupdatet
