### ISSUE TITLE
Als Anwender möchte ich einen Graph zu dem Kurs einer Kryptowährung angezeigt bekommen

### ISSUE THREAD

**Issue by AnnaSwd13** [c3ai-lab/cryptoAcademy#11]
Auf der Startseite möchte ich als Anwender eine Grafik über den Kursverlauf einer Kryptowährung haben.

**Comment by magdalenatsolaki** [comment]
@AnnaSwd13 ist das durch die Favoriten quasi umgesetzt?

![image](https://user-images.githubusercontent.com/12753112/146451499-866d7d31-f6e0-4c31-a639-7a90dbfc2db2.png)

**Comment by NotifierMan** [comment]
Durch die Favoriten und die Detailansichten einer Kryptowähung ist diese Anforderung aktuell umgesetzt.
![Screen Shot 2021-12-22 at 20 36 36](https://user-images.githubusercontent.com/5204104/147146269-3cfe52c5-9e9c-4118-92ae-d74c502fa501.png)
