### ISSUE TITLE
bei Routen den json-web-token auf Gültigkeit überprüfen und ggf. neuen Token generieren

### ISSUE THREAD

**Issue by AnnaSwd13** [c3ai-lab/cryptoAcademy#24]

**Comment by NotifierMan** [comment]
Sobald der JWT seine Gültigkeit verliert, wird der User vorerst wieder auf die Login-Seite geleitet. Damit verhindern wir, dass ein Entwickler sich über Fehlverhalten durch Anfragen mit einem abgelaufenen Token wundert.
