### ISSUE TITLE
Als Anwender möchte ich neben den Grafiken der Währungen deren Logos angezeigt bekommen

### ISSUE THREAD

**Issue by AnnaSwd13** [c3ai-lab/cryptoAcademy#46]

**Comment by NotifierMan** [comment]
![Screenshot from 2022-01-13 00-25-22](https://user-images.githubusercontent.com/5204104/149239122-5862d055-e555-47e5-a62b-f5f227e9938c.png)
![Screenshot from 2022-01-13 00-25-34](https://user-images.githubusercontent.com/5204104/149239125-fe32aca0-9d9c-4155-a0c1-4d50b008d996.png)
