### ISSUE TITLE
Als Anwender möchte ich Statusmeldungen bei Erfolg/ Nichterfolg haben

### ISSUE THREAD

**Issue by AnnaSwd13** [c3ai-lab/cryptoAcademy#49]
Als Anwender möchte ich nach dem Erfolg von beispielsweise der Registrierung oder dem Login eine Toast(-artige)-Nachricht haben. Das gleiche möchte ich an Stellen wo eine Aktion nicht erfolgreich ist.

**Comment by magdalenatsolaki** [comment]
backendseitig wurde App\Enum\MessageCodes

**Comment by NotifierMan** [comment]
Im allgemeinen erhält der Anwender mittlerweile Feedback zu seinen Aktionen. Für die fehlenden Fälle machen wir dedizierte Issues auf.
