### ISSUE TITLE
Als Anwender will ich meinen Account “reset-en” im Falle meine EUR Balance ist zu klein

### ISSUE THREAD

**Issue by sebastiangajek** [c3ai-lab/cryptoAcademy#52]
Reset für zum
Aufladen des Startkapitals

**Comment by AnnaSwd13** [comment]
löscht dann sämtliche Käufe, den Verlauf, alle Statistiken und später auch die Gilden/Bestenlisten

**Comment by magdalenatsolaki** [comment]
backendseitig implementiert
