### ISSUE TITLE
Als Anwender möchte ich auf meiner Profilseite die Skala der Grafik wählen 

### ISSUE THREAD

**Issue by AnnaSwd13** [c3ai-lab/cryptoAcademy#55]
Als Anwender möchte ich die Anzeige der x-Achse (Zeitraum) die Anzeige der y-Achse (Wert) an- und abschalten.

Skalierung 
1 Std, 1 Tag, 1 Woche, 1 Monat, 12 Monate

**Comment by urmel85** [comment]
Kann im User Profil gesetzt werden und wird in der Datenbank eingetragen. 
Im Moment werden beide Achsen in der Grafik MainChart.vue angezeigt, wenn einer der beiden Werte auf "An" ist,
