### ISSUE TITLE
Wallet: Im Wallet-View fehlt die Anzeige des Euro-Guthabens

### ISSUE THREAD

**Issue by maja13** [c3ai-lab/cryptoAcademy#89]

**Comment by NotifierMan** [comment]
Bei mir scheint unter `/wallets` alles da zu sein :thinking:

![Screenshot from 2022-01-12 10-09-15](https://user-images.githubusercontent.com/5204104/149097969-734c1026-7681-4365-9c60-1e9acc1ed875.png)

Kannst du das Problem auf dem aktuellen Master-Branch noch reproduzieren?

**Comment by NotifierMan** [comment]
Ich hatte gerade ein kurzes Gespräch mit @maja13: Es geht darum, dass in der Wallet-View nirgendwo der Euro-Kontostand angezeigt wird, mit dem man noch weitere Coins kaufen kann.

**Comment by NotifierMan** [comment]
Das Guthaben des Nutzers wird jetzt neben dem Gesamtwert seiner Coins angezeigt.

![Screenshot from 2022-01-12 23-36-16](https://user-images.githubusercontent.com/5204104/149234041-2089f0f3-4b6e-4901-9955-37ee2c311b8f.png)
